public class Driver {
    public static void main(String[] args) {
        GarageOwner theOwner = new GarageOwner("Chelsea", 20);
        Garage theGarage = new Garage(theOwner, new Car[7]);
        System.out.println("Creating car1 with 1st car constructor.");
        Car car1 = new Car(2019, "Honda", "CR-V", "black", 69);
        System.out.println("Adding car1");
        theGarage.addCar(1, car1);
        System.out.println("Creating car2 with 2nd car constructor.");
        Car car2 = new Car(2015, "Scion", "tC");
        System.out.println("Adding car2");
        theGarage.addCar(4, car2);
        System.out.println("Creating car3 with 3rd car constructor.");
        Car car3 = new Car();
        System.out.println("Adding car3");
        theGarage.addCar(6, car3);
        System.out.println("Trying to sell car1");
        theGarage.sellCar(3);
        System.out.printf("%s owns %d cars.\n", theOwner.getName(), theOwner.getCarsOwned());
        theGarage.showCertainCars(45);
        System.out.println("\n");

        //GarageOwner theOwner2 = new GarageOwner("Zach", 26);
        //Garage theGarage2 = new Garage(theOwner2, new Car[5]);
        //System.out.println("Creating car1b with 1st car constructor.");
        //Car car1b = new Car(2019, "Honda", "CR-V", "black", 53);
        //System.out.println("Adding car1b");
        //theGarage2.addCar(3, car1b);
        //System.out.println("Creating car2b with 2nd car constructor.");
        //Car car2b = new Car(2015, "Scion", "tC");
        //System.out.println("Adding car2b");
        //theGarage2.addCar(4, car2b);
        //System.out.println("Creating car3b with 3rd car constructor.");
        //Car car3b = new Car();
        //System.out.println("Adding car3b for the first time");
        //theGarage2.addCar(1, car3b);
        //System.out.println("Selling car3b");
        //theGarage2.sellCar(1);
        //System.out.println("Adding car3b after it's been sold");
        //theGarage2.addCar(1, car3b);
        //System.out.printf("%s owns %d cars.\n", theOwner2.getName(), theOwner2.getCarsOwned());
        //theGarage2.showCertainCars(65);
        //System.out.println("\n");
//
        //GarageOwner theOwner3 = new GarageOwner("Nicole", 27);
        //Garage theGarage3 = new Garage(theOwner3, new Car[10]);
        //System.out.println("Creating car1c with 1st car constructor.");
        //Car car1c = new Car(2023, "Chevrolet", "Silverado", "pink", 87);
        //System.out.println("Adding car1c");
        //theGarage3.addCar(7, car1c);
        //System.out.println("Creating car2c with 2nd car constructor.");
        //Car car2c = new Car(2004, "Toyota", "Rav-4");
        //System.out.println("Adding car2c");
        //theGarage3.addCar(9, car2c);
        //System.out.println("Creating car3c with 3rd car constructor.");
        //Car car3c = new Car();
        //System.out.println("Adding car3c");
        //theGarage3.addCar(1, car3c);
        //System.out.println("Selling car3c");
        //theGarage3.sellCar(9);
        //System.out.println("Selling car1c");
        //theGarage3.sellCar(7);
        //System.out.printf("%s owns %d cars.\n", theOwner3.getName(), theOwner3.getCarsOwned());
        //System.out.println("Car2c ConCat is " + car2c.getConditionCategory());
        //theGarage2.showCertainCars(83);
        //System.out.println("\n");
//
        //GarageOwner theOwner4 = new GarageOwner("Nicole", 27);
        //Garage theGarage4 = new Garage();
        //System.out.println("Creating car1d with 1st car constructor.");
        //Car car1d = new Car(1997, "Porsche", "Cayenne", "white", 129);
        //System.out.println("Adding car1d");
        //theGarage4.addCar(1, car1d);
        //System.out.println("Creating car2d with 2nd car constructor.");
        //Car car2d = new Car(2031, "Ford", "Mustang");
        //System.out.println("Adding car2d");
        //theGarage4.addCar(2, car2d);
        //System.out.println("Creating car3d with 3rd car constructor.");
        //Car car3d = new Car();
        //System.out.println("Adding car3d");
        //theGarage4.addCar(0, car3d);
        //System.out.println("Selling car3d");
        //theGarage4.sellCar(0);
        //System.out.println("Selling car1d");
        //theGarage4.sellCar(1);
        //System.out.printf("%s owns %d cars.\n", theOwner4.getName(), theOwner4.getCarsOwned());
        //System.out.println("Car2d ConCat is " + car2d.getConditionCategory());
        //theGarage2.showCertainCars(30);
        //System.out.println("\n");
    }
}
